name: CI
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os   :    [ubuntu-latest]
        scala:    [2.13.8]
        platform: [jvm, js]
        java :    [11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: coursier/setup-action@v1
        with:
          jvm: "adopt:${{ matrix.java }}"

      - name: Cache
        uses: coursier/cache-action@v6

      - name: Test JVM
        if: matrix.platform == 'jvm'
        run: sbt ++${{ matrix.scala }} validateJVM

      - name: Test JS
        if: matrix.platform == 'js'
        run: sbt ++${{ matrix.scala }} validateJS
